package ru.zavanton.booker.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AuthorEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuthorEntityAllPropertiesEquals(AuthorEntity expected, AuthorEntity actual) {
        assertAuthorEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertAuthorEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuthorEntityAllUpdatablePropertiesEquals(AuthorEntity expected, AuthorEntity actual) {
        assertAuthorEntityUpdatableFieldsEquals(expected, actual);
        assertAuthorEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuthorEntityAutoGeneratedPropertiesEquals(AuthorEntity expected, AuthorEntity actual) {
        assertThat(actual)
            .as("Verify AuthorEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuthorEntityUpdatableFieldsEquals(AuthorEntity expected, AuthorEntity actual) {
        assertThat(actual)
            .as("Verify AuthorEntity relevant properties")
            .satisfies(a -> assertThat(a.getFirstName()).as("check firstName").isEqualTo(expected.getFirstName()))
            .satisfies(a -> assertThat(a.getLastName()).as("check lastName").isEqualTo(expected.getLastName()))
            .satisfies(a -> assertThat(a.getFullName()).as("check fullName").isEqualTo(expected.getFullName()))
            .satisfies(a -> assertThat(a.getBiography()).as("check biography").isEqualTo(expected.getBiography()))
            .satisfies(a -> assertThat(a.getPhotoUrl()).as("check photoUrl").isEqualTo(expected.getPhotoUrl()))
            .satisfies(a -> assertThat(a.getBirthDate()).as("check birthDate").isEqualTo(expected.getBirthDate()))
            .satisfies(a -> assertThat(a.getDeathDate()).as("check deathDate").isEqualTo(expected.getDeathDate()))
            .satisfies(a -> assertThat(a.getNationality()).as("check nationality").isEqualTo(expected.getNationality()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuthorEntityUpdatableRelationshipsEquals(AuthorEntity expected, AuthorEntity actual) {
        // empty method
    }
}
