package ru.zavanton.booker.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BookTagEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookTagEntityAllPropertiesEquals(BookTagEntity expected, BookTagEntity actual) {
        assertBookTagEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertBookTagEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookTagEntityAllUpdatablePropertiesEquals(BookTagEntity expected, BookTagEntity actual) {
        assertBookTagEntityUpdatableFieldsEquals(expected, actual);
        assertBookTagEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookTagEntityAutoGeneratedPropertiesEquals(BookTagEntity expected, BookTagEntity actual) {
        assertThat(actual)
            .as("Verify BookTagEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookTagEntityUpdatableFieldsEquals(BookTagEntity expected, BookTagEntity actual) {
        // empty method

    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookTagEntityUpdatableRelationshipsEquals(BookTagEntity expected, BookTagEntity actual) {
        assertThat(actual)
            .as("Verify BookTagEntity relationships")
            .satisfies(a -> assertThat(a.getBook()).as("check book").isEqualTo(expected.getBook()))
            .satisfies(a -> assertThat(a.getTag()).as("check tag").isEqualTo(expected.getTag()));
    }
}
