package ru.zavanton.booker.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BookGenreEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookGenreEntityAllPropertiesEquals(BookGenreEntity expected, BookGenreEntity actual) {
        assertBookGenreEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertBookGenreEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookGenreEntityAllUpdatablePropertiesEquals(BookGenreEntity expected, BookGenreEntity actual) {
        assertBookGenreEntityUpdatableFieldsEquals(expected, actual);
        assertBookGenreEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookGenreEntityAutoGeneratedPropertiesEquals(BookGenreEntity expected, BookGenreEntity actual) {
        assertThat(actual)
            .as("Verify BookGenreEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookGenreEntityUpdatableFieldsEquals(BookGenreEntity expected, BookGenreEntity actual) {
        // empty method

    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookGenreEntityUpdatableRelationshipsEquals(BookGenreEntity expected, BookGenreEntity actual) {
        assertThat(actual)
            .as("Verify BookGenreEntity relationships")
            .satisfies(a -> assertThat(a.getBook()).as("check book").isEqualTo(expected.getBook()))
            .satisfies(a -> assertThat(a.getGenre()).as("check genre").isEqualTo(expected.getGenre()));
    }
}
