package ru.zavanton.booker.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BookAuthorEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookAuthorEntityAllPropertiesEquals(BookAuthorEntity expected, BookAuthorEntity actual) {
        assertBookAuthorEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertBookAuthorEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookAuthorEntityAllUpdatablePropertiesEquals(BookAuthorEntity expected, BookAuthorEntity actual) {
        assertBookAuthorEntityUpdatableFieldsEquals(expected, actual);
        assertBookAuthorEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookAuthorEntityAutoGeneratedPropertiesEquals(BookAuthorEntity expected, BookAuthorEntity actual) {
        assertThat(actual)
            .as("Verify BookAuthorEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookAuthorEntityUpdatableFieldsEquals(BookAuthorEntity expected, BookAuthorEntity actual) {
        assertThat(actual)
            .as("Verify BookAuthorEntity relevant properties")
            .satisfies(a -> assertThat(a.getIsPrimary()).as("check isPrimary").isEqualTo(expected.getIsPrimary()))
            .satisfies(a -> assertThat(a.getOrder()).as("check order").isEqualTo(expected.getOrder()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookAuthorEntityUpdatableRelationshipsEquals(BookAuthorEntity expected, BookAuthorEntity actual) {
        assertThat(actual)
            .as("Verify BookAuthorEntity relationships")
            .satisfies(a -> assertThat(a.getBook()).as("check book").isEqualTo(expected.getBook()))
            .satisfies(a -> assertThat(a.getAuthor()).as("check author").isEqualTo(expected.getAuthor()));
    }
}
