package ru.zavanton.booker.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BookCollectionEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookCollectionEntityAllPropertiesEquals(BookCollectionEntity expected, BookCollectionEntity actual) {
        assertBookCollectionEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertBookCollectionEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookCollectionEntityAllUpdatablePropertiesEquals(BookCollectionEntity expected, BookCollectionEntity actual) {
        assertBookCollectionEntityUpdatableFieldsEquals(expected, actual);
        assertBookCollectionEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookCollectionEntityAutoGeneratedPropertiesEquals(BookCollectionEntity expected, BookCollectionEntity actual) {
        assertThat(actual)
            .as("Verify BookCollectionEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookCollectionEntityUpdatableFieldsEquals(BookCollectionEntity expected, BookCollectionEntity actual) {
        assertThat(actual)
            .as("Verify BookCollectionEntity relevant properties")
            .satisfies(a -> assertThat(a.getPosition()).as("check position").isEqualTo(expected.getPosition()))
            .satisfies(a -> assertThat(a.getAddedAt()).as("check addedAt").isEqualTo(expected.getAddedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookCollectionEntityUpdatableRelationshipsEquals(BookCollectionEntity expected, BookCollectionEntity actual) {
        assertThat(actual)
            .as("Verify BookCollectionEntity relationships")
            .satisfies(a -> assertThat(a.getBook()).as("check book").isEqualTo(expected.getBook()))
            .satisfies(a -> assertThat(a.getCollection()).as("check collection").isEqualTo(expected.getCollection()));
    }
}
