package ru.zavanton.booker.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static ru.zavanton.booker.domain.AssertUtils.bigDecimalCompareTo;

public class BookEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookEntityAllPropertiesEquals(BookEntity expected, BookEntity actual) {
        assertBookEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertBookEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookEntityAllUpdatablePropertiesEquals(BookEntity expected, BookEntity actual) {
        assertBookEntityUpdatableFieldsEquals(expected, actual);
        assertBookEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookEntityAutoGeneratedPropertiesEquals(BookEntity expected, BookEntity actual) {
        assertThat(actual)
            .as("Verify BookEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookEntityUpdatableFieldsEquals(BookEntity expected, BookEntity actual) {
        assertThat(actual)
            .as("Verify BookEntity relevant properties")
            .satisfies(a -> assertThat(a.getIsbn()).as("check isbn").isEqualTo(expected.getIsbn()))
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getCoverImageUrl()).as("check coverImageUrl").isEqualTo(expected.getCoverImageUrl()))
            .satisfies(a -> assertThat(a.getPageCount()).as("check pageCount").isEqualTo(expected.getPageCount()))
            .satisfies(a -> assertThat(a.getPublicationDate()).as("check publicationDate").isEqualTo(expected.getPublicationDate()))
            .satisfies(a -> assertThat(a.getLanguage()).as("check language").isEqualTo(expected.getLanguage()))
            .satisfies(a ->
                assertThat(a.getAverageRating())
                    .as("check averageRating")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getAverageRating())
            )
            .satisfies(a -> assertThat(a.getTotalRatings()).as("check totalRatings").isEqualTo(expected.getTotalRatings()))
            .satisfies(a -> assertThat(a.getTotalReviews()).as("check totalReviews").isEqualTo(expected.getTotalReviews()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookEntityUpdatableRelationshipsEquals(BookEntity expected, BookEntity actual) {
        assertThat(actual)
            .as("Verify BookEntity relationships")
            .satisfies(a -> assertThat(a.getPublisher()).as("check publisher").isEqualTo(expected.getPublisher()));
    }
}
