package ru.zavanton.booker.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CollectionEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCollectionEntityAllPropertiesEquals(CollectionEntity expected, CollectionEntity actual) {
        assertCollectionEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertCollectionEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCollectionEntityAllUpdatablePropertiesEquals(CollectionEntity expected, CollectionEntity actual) {
        assertCollectionEntityUpdatableFieldsEquals(expected, actual);
        assertCollectionEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCollectionEntityAutoGeneratedPropertiesEquals(CollectionEntity expected, CollectionEntity actual) {
        assertThat(actual)
            .as("Verify CollectionEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCollectionEntityUpdatableFieldsEquals(CollectionEntity expected, CollectionEntity actual) {
        assertThat(actual)
            .as("Verify CollectionEntity relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getIsPublic()).as("check isPublic").isEqualTo(expected.getIsPublic()))
            .satisfies(a -> assertThat(a.getBookCount()).as("check bookCount").isEqualTo(expected.getBookCount()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCollectionEntityUpdatableRelationshipsEquals(CollectionEntity expected, CollectionEntity actual) {
        // empty method
    }
}
