package ru.zavanton.booker.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CommentEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommentEntityAllPropertiesEquals(CommentEntity expected, CommentEntity actual) {
        assertCommentEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertCommentEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommentEntityAllUpdatablePropertiesEquals(CommentEntity expected, CommentEntity actual) {
        assertCommentEntityUpdatableFieldsEquals(expected, actual);
        assertCommentEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommentEntityAutoGeneratedPropertiesEquals(CommentEntity expected, CommentEntity actual) {
        assertThat(actual)
            .as("Verify CommentEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommentEntityUpdatableFieldsEquals(CommentEntity expected, CommentEntity actual) {
        assertThat(actual)
            .as("Verify CommentEntity relevant properties")
            .satisfies(a -> assertThat(a.getContent()).as("check content").isEqualTo(expected.getContent()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommentEntityUpdatableRelationshipsEquals(CommentEntity expected, CommentEntity actual) {
        assertThat(actual)
            .as("Verify CommentEntity relationships")
            .satisfies(a -> assertThat(a.getReview()).as("check review").isEqualTo(expected.getReview()));
    }
}
