package ru.zavanton.booker.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class GenreEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGenreEntityAllPropertiesEquals(GenreEntity expected, GenreEntity actual) {
        assertGenreEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertGenreEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGenreEntityAllUpdatablePropertiesEquals(GenreEntity expected, GenreEntity actual) {
        assertGenreEntityUpdatableFieldsEquals(expected, actual);
        assertGenreEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGenreEntityAutoGeneratedPropertiesEquals(GenreEntity expected, GenreEntity actual) {
        assertThat(actual)
            .as("Verify GenreEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGenreEntityUpdatableFieldsEquals(GenreEntity expected, GenreEntity actual) {
        assertThat(actual)
            .as("Verify GenreEntity relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getSlug()).as("check slug").isEqualTo(expected.getSlug()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGenreEntityUpdatableRelationshipsEquals(GenreEntity expected, GenreEntity actual) {
        // empty method
    }
}
