package ru.zavanton.booker.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PublisherEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublisherEntityAllPropertiesEquals(PublisherEntity expected, PublisherEntity actual) {
        assertPublisherEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertPublisherEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublisherEntityAllUpdatablePropertiesEquals(PublisherEntity expected, PublisherEntity actual) {
        assertPublisherEntityUpdatableFieldsEquals(expected, actual);
        assertPublisherEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublisherEntityAutoGeneratedPropertiesEquals(PublisherEntity expected, PublisherEntity actual) {
        assertThat(actual)
            .as("Verify PublisherEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublisherEntityUpdatableFieldsEquals(PublisherEntity expected, PublisherEntity actual) {
        assertThat(actual)
            .as("Verify PublisherEntity relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getWebsiteUrl()).as("check websiteUrl").isEqualTo(expected.getWebsiteUrl()))
            .satisfies(a -> assertThat(a.getLogoUrl()).as("check logoUrl").isEqualTo(expected.getLogoUrl()))
            .satisfies(a -> assertThat(a.getFoundedDate()).as("check foundedDate").isEqualTo(expected.getFoundedDate()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublisherEntityUpdatableRelationshipsEquals(PublisherEntity expected, PublisherEntity actual) {
        // empty method
    }
}
