package ru.zavanton.booker.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RatingEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRatingEntityAllPropertiesEquals(RatingEntity expected, RatingEntity actual) {
        assertRatingEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertRatingEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRatingEntityAllUpdatablePropertiesEquals(RatingEntity expected, RatingEntity actual) {
        assertRatingEntityUpdatableFieldsEquals(expected, actual);
        assertRatingEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRatingEntityAutoGeneratedPropertiesEquals(RatingEntity expected, RatingEntity actual) {
        assertThat(actual)
            .as("Verify RatingEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRatingEntityUpdatableFieldsEquals(RatingEntity expected, RatingEntity actual) {
        assertThat(actual)
            .as("Verify RatingEntity relevant properties")
            .satisfies(a -> assertThat(a.getRating()).as("check rating").isEqualTo(expected.getRating()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRatingEntityUpdatableRelationshipsEquals(RatingEntity expected, RatingEntity actual) {
        assertThat(actual)
            .as("Verify RatingEntity relationships")
            .satisfies(a -> assertThat(a.getBook()).as("check book").isEqualTo(expected.getBook()));
    }
}
