package ru.zavanton.booker.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ReadingStatusEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReadingStatusEntityAllPropertiesEquals(ReadingStatusEntity expected, ReadingStatusEntity actual) {
        assertReadingStatusEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertReadingStatusEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReadingStatusEntityAllUpdatablePropertiesEquals(ReadingStatusEntity expected, ReadingStatusEntity actual) {
        assertReadingStatusEntityUpdatableFieldsEquals(expected, actual);
        assertReadingStatusEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReadingStatusEntityAutoGeneratedPropertiesEquals(ReadingStatusEntity expected, ReadingStatusEntity actual) {
        assertThat(actual)
            .as("Verify ReadingStatusEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReadingStatusEntityUpdatableFieldsEquals(ReadingStatusEntity expected, ReadingStatusEntity actual) {
        assertThat(actual)
            .as("Verify ReadingStatusEntity relevant properties")
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getStartedDate()).as("check startedDate").isEqualTo(expected.getStartedDate()))
            .satisfies(a -> assertThat(a.getFinishedDate()).as("check finishedDate").isEqualTo(expected.getFinishedDate()))
            .satisfies(a -> assertThat(a.getCurrentPage()).as("check currentPage").isEqualTo(expected.getCurrentPage()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReadingStatusEntityUpdatableRelationshipsEquals(ReadingStatusEntity expected, ReadingStatusEntity actual) {
        assertThat(actual)
            .as("Verify ReadingStatusEntity relationships")
            .satisfies(a -> assertThat(a.getBook()).as("check book").isEqualTo(expected.getBook()));
    }
}
