package ru.zavanton.booker.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ReviewEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReviewEntityAllPropertiesEquals(ReviewEntity expected, ReviewEntity actual) {
        assertReviewEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertReviewEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReviewEntityAllUpdatablePropertiesEquals(ReviewEntity expected, ReviewEntity actual) {
        assertReviewEntityUpdatableFieldsEquals(expected, actual);
        assertReviewEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReviewEntityAutoGeneratedPropertiesEquals(ReviewEntity expected, ReviewEntity actual) {
        assertThat(actual)
            .as("Verify ReviewEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReviewEntityUpdatableFieldsEquals(ReviewEntity expected, ReviewEntity actual) {
        assertThat(actual)
            .as("Verify ReviewEntity relevant properties")
            .satisfies(a -> assertThat(a.getContent()).as("check content").isEqualTo(expected.getContent()))
            .satisfies(a -> assertThat(a.getRating()).as("check rating").isEqualTo(expected.getRating()))
            .satisfies(a -> assertThat(a.getContainsSpoilers()).as("check containsSpoilers").isEqualTo(expected.getContainsSpoilers()))
            .satisfies(a -> assertThat(a.getHelpfulCount()).as("check helpfulCount").isEqualTo(expected.getHelpfulCount()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReviewEntityUpdatableRelationshipsEquals(ReviewEntity expected, ReviewEntity actual) {
        assertThat(actual)
            .as("Verify ReviewEntity relationships")
            .satisfies(a -> assertThat(a.getBook()).as("check book").isEqualTo(expected.getBook()));
    }
}
