package ru.zavanton.booker.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TagEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTagEntityAllPropertiesEquals(TagEntity expected, TagEntity actual) {
        assertTagEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertTagEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTagEntityAllUpdatablePropertiesEquals(TagEntity expected, TagEntity actual) {
        assertTagEntityUpdatableFieldsEquals(expected, actual);
        assertTagEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTagEntityAutoGeneratedPropertiesEquals(TagEntity expected, TagEntity actual) {
        assertThat(actual)
            .as("Verify TagEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTagEntityUpdatableFieldsEquals(TagEntity expected, TagEntity actual) {
        assertThat(actual)
            .as("Verify TagEntity relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getSlug()).as("check slug").isEqualTo(expected.getSlug()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTagEntityUpdatableRelationshipsEquals(TagEntity expected, TagEntity actual) {
        // empty method
    }
}
